// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGt4jMwP771bm5mf0MeSG_6WTyF9A5Svk',
    appId: '1:512590954876:web:bbfc64fad86980c31124f9',
    messagingSenderId: '512590954876',
    projectId: 'chef-31f64',
    authDomain: 'chef-31f64.firebaseapp.com',
    storageBucket: 'chef-31f64.firebasestorage.app',
    measurementId: 'G-2F6FMPB862',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClriieWU7oRRltYE8CXQTUo8FiyqoEx3E',
    appId: '1:512590954876:android:e5e3b416b74581b71124f9',
    messagingSenderId: '512590954876',
    projectId: 'chef-31f64',
    storageBucket: 'chef-31f64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxoMDp9DdfQaYMRgusSC1jSBa83uEcyv8',
    appId: '1:512590954876:ios:8992361cb4d6acb11124f9',
    messagingSenderId: '512590954876',
    projectId: 'chef-31f64',
    storageBucket: 'chef-31f64.firebasestorage.app',
    iosBundleId: 'com.example.chef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxoMDp9DdfQaYMRgusSC1jSBa83uEcyv8',
    appId: '1:512590954876:ios:8992361cb4d6acb11124f9',
    messagingSenderId: '512590954876',
    projectId: 'chef-31f64',
    storageBucket: 'chef-31f64.firebasestorage.app',
    iosBundleId: 'com.example.chef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGt4jMwP771bm5mf0MeSG_6WTyF9A5Svk',
    appId: '1:512590954876:web:47e82d304c00d2f31124f9',
    messagingSenderId: '512590954876',
    projectId: 'chef-31f64',
    authDomain: 'chef-31f64.firebaseapp.com',
    storageBucket: 'chef-31f64.firebasestorage.app',
    measurementId: 'G-20F7LC5NE9',
  );
}
